### PR TITLE
fix(config): renamed default client causes error

### LINKED ISSUE #60: [Bug] renaming default client will lead to preImportPath error
### Version

v0.5.0

### Description

Changing the name of the `default` client will throw an error for the preImportPath.

### Expected Behavior

Renaming the `default` client shouldn't impact functionality.

### Relevant log output

```shell
2024/01/15 15:24:52 preImportPath for client "default" can't be empty, please provide a valid path to the directory you want seasonpacks to be hardlinked to
```

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nuxencs**
Fixes #60

### CODE REVIEW

File: internal/config/config.go [hunk 1]
```diff
@@ -267,18 +266,9 @@ func New(configPath string, version string) *AppConfig {
 
 func (c *AppConfig) defaults() {
 	c.Config = &domain.Config{
-		Version: "dev",
-		Host:    "0.0.0.0",
-		Port:    42069,
-		Clients: map[string]*domain.Client{
```
Comment (zze0s) [inline internal/config/config.go:273]: You should probably still initialize the map to not cause panics if it tries to lookup a key.

`Clients: map[string]*domain.Client{},`

**Review by zze0s — APPROVED** [review]
LGTM!
